-- Seed records — verifiable real declassified material from NARA/CIA/NASA/AARO.
-- Used so the UI is testable before the full ingest pipeline runs.
-- Source URLs are stable canonical landing pages.

INSERT INTO records (title, agency, unsealed_date, collection_id, source_url, description, thumbnail_url) VALUES
('JFK Assassination Records — 2025 Release Tranche', 'NARA', '2025-03-18', 'JFK Assassination Records Collection', 'https://www.archives.gov/research/jfk/release-2025', 'Final tranche of records released under EO 14176 directing full disclosure of records related to the assassination of President John F. Kennedy.', NULL),
('Family Jewels — Internal CIA Memoranda 1973', 'CIA', '2007-06-26', 'CREST', 'https://www.cia.gov/readingroom/collection/family-jewels', 'Compilation of memoranda documenting potentially illegal CIA activities from 1959–1973, ordered compiled by Director Schlesinger and released to the public in 2007.', 'https://www.cia.gov/readingroom/sites/default/files/styles/medium/public/family-jewels.jpg'),
('STARGATE — Remote Viewing Program Files', 'CIA', '2017-01-17', 'CREST', 'https://www.cia.gov/readingroom/collection/stargate', 'Records concerning the CIA-sponsored research program into psychic phenomena and remote viewing, conducted from the 1970s through the 1990s.', NULL),
('Apollo 11 Mission Operations Report', 'NASA', '1969-11-15', 'Apollo Program Records', 'https://www.nasa.gov/history/SP-4029/Apollo_11.htm', 'Post-flight mission operations report covering trajectory, lunar surface activity, and recovery for the first crewed lunar landing.', NULL),
('AARO Historical Record Report Volume I', 'AARO', '2024-03-08', 'AARO Public Releases', 'https://www.aaro.mil/Portals/136/PDFs/HRRV1-08-Mar-2024-Final.pdf', 'Department of Defense All-domain Anomaly Resolution Office historical report on the United States Government''s involvement with Unidentified Anomalous Phenomena (UAP) from 1945 to 2023.', NULL),
('Project BLUE BOOK Case Files', 'NARA', '1976-01-01', 'RG 341 — Records of HQ USAF', 'https://www.archives.gov/research/military/air-force/ufos', 'Official records of the U.S. Air Force investigation into Unidentified Flying Object reports, 1947–1969.', NULL),
('NASA UAP Independent Study Team Final Report', 'NASA', '2023-09-14', 'UAP Studies', 'https://science.nasa.gov/wp-content/uploads/2023/09/uap-independent-study-team-final-report.pdf', 'Findings and recommendations from the independent study team commissioned by NASA to examine UAP from a scientific perspective.', NULL),
('Operation MONGOOSE Records', 'CIA', '1998-09-30', 'JFK Assassination Records Collection', 'https://www.archives.gov/research/jfk/select-committee-report/part-3.html', 'Records pertaining to the U.S. covert action program against the Cuban government, 1961–1962.', NULL),
('MKULTRA — Project Records', 'CIA', '1977-08-01', 'CREST', 'https://www.cia.gov/readingroom/collection/mkultra', 'Surviving records of the CIA''s research program into behavioral modification, including chemical, biological, and radiological methods.', NULL),
('Pentagon Papers — Declassified Edition', 'NARA', '2011-06-13', 'RG 330 — Records of the Office of the Secretary of Defense', 'https://www.archives.gov/research/pentagon-papers', '7,000-page Department of Defense study of U.S. political-military involvement in Vietnam from 1945 to 1967, released in full in 2011.', NULL),
('NDC Quarterly Release List — 2025 Q4', 'NARA', '2025-12-15', 'National Declassification Center', 'https://www.archives.gov/declassification/ndc/release-and-disclosure', 'Quarterly list of newly declassified records made available by the National Declassification Center.', NULL),
('Skylab Mission Reports — Workshop Operations', 'NASA', '1979-04-12', 'Skylab Program Records', 'https://www.nasa.gov/history/skylab', 'Operational reports from the first United States space station, 1973–1974.', NULL);
